### ISSUE TITLE
New Trident docs have 'find_multipaths yes';  readthedocs show 'find_multipaths no'

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#22] opened 2021-11-17 12:29 UTC
Page: [Prepare the worker node](https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html)

Please correct the doc pages to show the correct setting for 'find_multipaths' in the iscsi preparation section.

Referencing the following in the new doc pages:

https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html

4. Enable multipathing:
sudo tee /etc/multipath.conf <←'EOF'
defaults {
user_friendly_names yes
**find_multipaths yes**   <--------
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----------------------------------------------------------

Compare to: 
https://netapp-trident.readthedocs.io/en/latest/kubernetes/operations/tasks/worker.html?highlight=find_multipaths

4. Enable multipathing:
sudo mpathconf --enable --with_multipathd y --**find_multipaths n**    <-----------------
Note:  You should ensure the /etc/multipath.conf file contains find_multipaths **no** under the defaults section.  <----

Which is correct?

**Comment by juliantap** [comment] 2021-11-17 20:12
Hi @crossond, 

In your comment, it looks like you are comparing the multipath commands for Ubuntu/Debian (in your first example) against RHEL/CentOS (in your second example). 

Did you mean to compare Ubuntu to Ubuntu instead? I do see a discrepancy there. Please confirm so I can follow up. 

### Here is Ubuntu on [RTD](https://netapp-trident.readthedocs.io/en/latest/kubernetes/operations/tasks/worker.html?highlight=worker%20node).

```
sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    .
    .
    **find_multipaths no**
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
```

### Versus Ubuntu on [docs.netapp.com](https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html#iscsi-volumes)

```
sudo tee /etc/multipath.conf <←'EOF'
defaults {
user_friendly_names yes
**find_multipaths yes**
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
```

**Comment by crossond** [comment] 2021-11-17 20:50
Apologies,  I didn’t notice I copy/pasted from different sections.

     -	Step 4 from the RTD sets find_multipath = no,  for both RHEL and UBUNTU.

     -	In docs.netapp.com,  find_multipath is only mentioned for Ubuntu/Debian, and is set = yes.
        It is not mentioned at all for RHEL.

    -> My question is:   What is the correct setting for  'find_multipath',   for iscsi of any Linux flavor.

The docs should be updated as appropriate.
Thank You for your follow up.

Regards,
David Crosson

**Comment by juliantap** [comment] 2021-11-18 20:09
@crossond --thanks for the clarification! I'll take this to engineering to get it resolved. Thanks!

**Comment by juliantap** [comment] 2021-11-22 21:04
Hi @crossond, Ben S confirmed the previous RTD version is the recommended approach. I've restored the docs.netapp.com docs to that RTD version (`find_multipath no`). The build should be merged to production in about an hour. 

Many thanks for catching this!

J

**Closed by juliantap** 2021-11-22 21:04 UTC
